### ISSUE TITLE
Header line is not recognized

### ISSUE THREAD

**Issue by CodeDuck42** [marlosoft/symfony-profiler-extension#1]
The symfony debug link header is not recognized. It seems newer chrome versions report the headers all in lowercase.

Used browser: Vivaldi | 2.5.1525.40 (Stable channel) (64-Bit)

**Comment by magikid** [comment]
I'm also having this problem.  I would love to see #2 merged in and deployed so that I could use this plugin.

**Comment by factorin-j** [comment]
Merged #2
